#!/usr/bin/env python3
# coding: utf-8
"""Entire checker module."""
from rbls import *


def check(ip):
    """Check and print listed rbl only.

    :type ip: str
    """
    crate_server = 'localhost'
    crate_port = '4200'
    rip = '.'.join(reversed(ip.split('.')))
    access_redhawk_org.run(crate_server, crate_port, rip)
    accredit_habeas_com.run(crate_server, crate_port, rip)
    admin_bl_kundenserver_de.run(crate_server, crate_port, rip)
    all_rbl_jp.run(crate_server, crate_port, rip)
    all_s5h_net.run(crate_server, crate_port, rip)
    all_spam - rbl_fr.run(crate_server, crate_port, rip)
    aspews_ext_sorbs_net.run(crate_server, crate_port, rip)
    auth_spamrats_com.run(crate_server, crate_port, rip)
    b_barracudacentral_org.run(crate_server, crate_port, rip)
    backscatter_spameatingmonkey_net.run(crate_server, crate_port, rip)
    bad_psky_me.run(crate_server, crate_port, rip)
    bl_blocklist_de.run(crate_server, crate_port, rip)
    bl_drmx_org.run(crate_server, crate_port, rip)
    bl_emailbasura_org.run(crate_server, crate_port, rip)
    bl_fmb_la.run(crate_server, crate_port, rip)
    bl_konstant_no.run(crate_server, crate_port, rip)
    bl_mailspike_net.run(crate_server, crate_port, rip)
    bl_mav_com_br.run(crate_server, crate_port, rip)
    bl_mipspace_com.run(crate_server, crate_port, rip)
    bl_nszones_com.run(crate_server, crate_port, rip)
    bl_scientificspam_net.run(crate_server, crate_port, rip)
    bl_score_senderscore_com.run(crate_server, crate_port, rip)
    bl_spamcannibal_org.run(crate_server, crate_port, rip)
    bl_spamcop_net.run(crate_server, crate_port, rip)
    bl_spameatingmonkey_net.run(crate_server, crate_port, rip)
    bl_spamstinks_com.run(crate_server, crate_port, rip)
    bl_suomispam_net.run(crate_server, crate_port, rip)
    bl_tiopan_com.run(crate_server, crate_port, rip)
    blackholes_scconsult_com.run(crate_server, crate_port, rip)
    blacklist_mail_ops_asp_att_net.run(crate_server, crate_port, rip)
    blacklist_mailrelay_att_net.run(crate_server, crate_port, rip)
    blacklist_sci_kun_nl.run(crate_server, crate_port, rip)
    blacklist_sequoia_ops_asp_att_net.run(crate_server, crate_port, rip)
    blacklist_woody_ch.run(crate_server, crate_port, rip)
    block_ascams_com.run(crate_server, crate_port, rip)
    bogons_cymru_com.run(crate_server, crate_port, rip)
    bsb_empty_us.run(crate_server, crate_port, rip)
    bsb_spamlookup_net.run(crate_server, crate_port, rip)
    cbl_abuseat_org.run(crate_server, crate_port, rip)
    cbl_anti - spam_org_cn.run(crate_server, crate_port, rip)
    cblless_anti - spam_org_cn.run(crate_server, crate_port, rip)
    cblplus_anti - spam_org_cn.run(crate_server, crate_port, rip)
    cdl_anti - spam_org_cn.run(crate_server, crate_port, rip)
    cidr_bl_mcafee_com.run(crate_server, crate_port, rip)
    cml_anti - spam_org_cn.run(crate_server, crate_port, rip)
    combined_abuse_ch.run(crate_server, crate_port, rip)
    combined_rbl_msrbl_net.run(crate_server, crate_port, rip)
    db_wpbl_info.run(crate_server, crate_port, rip)
    dnsbl1_uceprotect_net.run(crate_server, crate_port, rip)
    dnsbl2_uceprotect_net.run(crate_server, crate_port, rip)
    dnsbl3_uceprotect_net.run(crate_server, crate_port, rip)
    dnsbl1_dnsbl_borderware_com.run(crate_server, crate_port, rip)
    dnsbl2_dnsbl_borderware_com.run(crate_server, crate_port, rip)
    dnsbl3_dnsbl_borderware_com.run(crate_server, crate_port, rip)
    dnsbl_anticaptcha_net.run(crate_server, crate_port, rip)
    dnsbl_aspnet_hu.run(crate_server, crate_port, rip)
    dnsbl_calivent_com_pe.run(crate_server, crate_port, rip)
    dnsbl_cobion_com.run(crate_server, crate_port, rip)
    dnsbl_cyberlogic_net.run(crate_server, crate_port, rip)
    dnsbl_dronebl_org.run(crate_server, crate_port, rip)
    dnsbl_forefront_microsoft_com.run(crate_server, crate_port, rip)
    dnsbl_inps_de.run(crate_server, crate_port, rip)
    dnsbl_ipocalypse_net.run(crate_server, crate_port, rip)
    dnsbl_justspam_org.run(crate_server, crate_port, rip)
    dnsbl_kempt_net.run(crate_server, crate_port, rip)
    dnsbl_madavi_de.run(crate_server, crate_port, rip)
    dnsbl_mcu_edu_tw.run(crate_server, crate_port, rip)
    dnsbl_net_ua.run(crate_server, crate_port, rip)
    dnsbl_openresolvers_org.run(crate_server, crate_port, rip)
    dnsbl_proxybl_org.run(crate_server, crate_port, rip)
    dnsbl_rizon_net.run(crate_server, crate_port, rip)
    dnsbl_rv - soft_info.run(crate_server, crate_port, rip)
    dnsbl_rymsho_ru.run(crate_server, crate_port, rip)
    dnsbl_sorbs_net.run(crate_server, crate_port, rip)
    dnsbl_spfbl_net.run(crate_server, crate_port, rip)
    dnsbl_tornevall_org.run(crate_server, crate_port, rip)
    dnsbl_zapbl_net.run(crate_server, crate_port, rip)
    dnsblchile_org.run(crate_server, crate_port, rip)
    dnsrbl_org.run(crate_server, crate_port, rip)
    dnsrbl_swinog_ch.run(crate_server, crate_port, rip)
    drone_abuse_ch.run(crate_server, crate_port, rip)
    duinv_aupads_org.run(crate_server, crate_port, rip)
    dul_blackhole_cantv_net.run(crate_server, crate_port, rip)
    dul_dnsbl_borderware_com.run(crate_server, crate_port, rip)
    dul_pacifier_net.run(crate_server, crate_port, rip)
    dyna_spamrats_com.run(crate_server, crate_port, rip)
    dynip_rothen_com.run(crate_server, crate_port, rip)
    exitnodes_tor_dnsbl_sectoor_de.run(crate_server, crate_port, rip)
    feb_spamlab_com.run(crate_server, crate_port, rip)
    fnrbl_fast_net.run(crate_server, crate_port, rip)
    forbidden_icm_edu_pl.run(crate_server, crate_port, rip)
    free_v4bl_org.run(crate_server, crate_port, rip)
    gl_suomispam_net.run(crate_server, crate_port, rip)
    hil_habeas_com.run(crate_server, crate_port, rip)
    hog_blackhole_cantv_net.run(crate_server, crate_port, rip)
    hostkarma_junkemailfilter_com.run(crate_server, crate_port, rip)
    images_rbl_msrbl_net.run(crate_server, crate_port, rip)
    ipbl_mailhosts_org.run(crate_server, crate_port, rip)
    ipbl_zeustracker_abuse_ch.run(crate_server, crate_port, rip)
    ips_backscatterer_org.run(crate_server, crate_port, rip)
    ipv6_rbl_choon_net.run(crate_server, crate_port, rip)
    ispmx_pofon_foobar_hu.run(crate_server, crate_port, rip)
    ix_dnsbl_manitu_net.run(crate_server, crate_port, rip)
    ixhash_spameatingmonkey_net.run(crate_server, crate_port, rip)
    korea_services_net.run(crate_server, crate_port, rip)
    l2_apews_org.run(crate_server, crate_port, rip)
    list_blogspambl_com.run(crate_server, crate_port, rip)
    mail - abuse_blacklist_jippg_org.run(crate_server, crate_port, rip)
    multi_surbl_org.run(crate_server, crate_port, rip)
    netbl_spameatingmonkey_net.run(crate_server, crate_port, rip)
    netblock_pedantic_org.run(crate_server, crate_port, rip)
    netscan_rbl_blockedservers_com.run(crate_server, crate_port, rip)
    noptr_spamrats_com.run(crate_server, crate_port, rip)
    orvedb_aupads_org.run(crate_server, crate_port, rip)
    pbl_spamhaus_org.run(crate_server, crate_port, rip)
    phishing_rbl_msrbl_net.run(crate_server, crate_port, rip)
    pofon_foobar_hu.run(crate_server, crate_port, rip)
    psbl_surriel_com.run(crate_server, crate_port, rip)
    q_mail - abuse_com.run(crate_server, crate_port, rip)
    r_mail - abuse_com.run(crate_server, crate_port, rip)
    rbl2_triumf_ca.run(crate_server, crate_port, rip)
    rbl_abuse_ro.run(crate_server, crate_port, rip)
    rbl_blakjak_net.run(crate_server, crate_port, rip)
    rbl_blockedservers_com.run(crate_server, crate_port, rip)
    rbl_choon_net.run(crate_server, crate_port, rip)
    rbl_dns - servicios_com.run(crate_server, crate_port, rip)
    rbl_efnetrbl_org.run(crate_server, crate_port, rip)
    rbl_fasthosts_co_uk.run(crate_server, crate_port, rip)
    rbl_interserver_net.run(crate_server, crate_port, rip)
    rbl_iprange_net.run(crate_server, crate_port, rip)
    rbl_lugh_ch.run(crate_server, crate_port, rip)
    rbl_megarbl_net.run(crate_server, crate_port, rip)
    rbl_polarcomm_net.run(crate_server, crate_port, rip)
    rbl_rbldns_ru.run(crate_server, crate_port, rip)
    rbl_schulte_org.run(crate_server, crate_port, rip)
    rbl_spamlab_com.run(crate_server, crate_port, rip)
    rbl_talkactive_net.run(crate_server, crate_port, rip)
    rbl_tdk_net.run(crate_server, crate_port, rip)
    rbl_zenon_net.run(crate_server, crate_port, rip)
    relays_bl_kundenserver_de.run(crate_server, crate_port, rip)
    relays_nether_net.run(crate_server, crate_port, rip)
    rhsbl_blackhole_cantv_net.run(crate_server, crate_port, rip)
    rot_blackhole_cantv_net.run(crate_server, crate_port, rip)
    rsbl_aupads_org.run(crate_server, crate_port, rip)
    safe_dnsbl_prs_proofpoint_com.run(crate_server, crate_port, rip)
    sbl - xbl_spamhaus_org.run(crate_server, crate_port, rip)
    schizo - bl_kundenserver_de.run(crate_server, crate_port, rip)
    service_mailblacklist_com.run(crate_server, crate_port, rip)
    short_rbl_jp.run(crate_server, crate_port, rip)
    shortlist_mailhosts_org.run(crate_server, crate_port, rip)
    singular_ttk_pte_hu.run(crate_server, crate_port, rip)
    sohul_habeas_com.run(crate_server, crate_port, rip)
    spam_abuse_ch.run(crate_server, crate_port, rip)
    spam_blackhole_cantv_net.run(crate_server, crate_port, rip)
    spam_dnsbl_anonmails_de.run(crate_server, crate_port, rip)
    spam_dnsbl_sorbs_net.run(crate_server, crate_port, rip)
    spam_pedantic_org.run(crate_server, crate_port, rip)
    spam_rbl - dns_com.run(crate_server, crate_port, rip)
    spam_rbl_blockedservers_com.run(crate_server, crate_port, rip)
    spam_rbl_msrbl_net.run(crate_server, crate_port, rip)
    spam_spamrats_com.run(crate_server, crate_port, rip)
    spamblock_kundenserver_de.run(crate_server, crate_port, rip)
    spambot_bls_digibase_ca.run(crate_server, crate_port, rip)
    spamguard_leadmon_net.run(crate_server, crate_port, rip)
    spamlist_or_kr.run(crate_server, crate_port, rip)
    spamrbl_imp_ch.run(crate_server, crate_port, rip)
    spamsources_fabel_dk.run(crate_server, crate_port, rip)
    srnblack_surgate_net.run(crate_server, crate_port, rip)
    st_technovision_dk.run(crate_server, crate_port, rip)
    superblock_ascams_com.run(crate_server, crate_port, rip)
    tor_dan_me_uk.run(crate_server, crate_port, rip)
    tor_dnsbl_sectoor_de.run(crate_server, crate_port, rip)
    tor_efnet_org.run(crate_server, crate_port, rip)
    truncate_gbudb_net.run(crate_server, crate_port, rip)
    ubl_lashback_com.run(crate_server, crate_port, rip)
    ubl_unsubscore_com.run(crate_server, crate_port, rip)
    v4_fullbogons_cymru_com.run(crate_server, crate_port, rip)
    virbl_bit_nl.run(crate_server, crate_port, rip)
    virbl_dnsbl_bit_nl.run(crate_server, crate_port, rip)
    virus_rbl_jp.run(crate_server, crate_port, rip)
    virus_rbl_msrbl_net.run(crate_server, crate_port, rip)
    whois_rfc - ignorant_org.run(crate_server, crate_port, rip)
    work_drbl_caravan_ru.run(crate_server, crate_port, rip)
    work_drbl_gremlin_ru.run(crate_server, crate_port, rip)
    work_drbldf_dsbl_ru.run(crate_server, crate_port, rip)
    wormrbl_imp_ch.run(crate_server, crate_port, rip)
    worms - bl_kundenserver_de.run(crate_server, crate_port, rip)
    xpews_mailhosts_org.run(crate_server, crate_port, rip)
    z_mailspike_net.run(crate_server, crate_port, rip)
    zen_spamhaus_org.run(crate_server, crate_port, rip)
    zerospam_fusionzero_com.run(crate_server, crate_port, rip)


def dispatch(entry):
    """Send each IP in a range to the check otherwise send only one IP."""
    from ipaddress import ip_network
    if '/32' in entry:
        check(entry.split('/')[0])
    else:
        for ip in ip_network(entry).hosts():
            check(ip)
