from typing import List

rbls: List = [
    'access.redhawk.org',
    'accredit.habeas.com',
    'admin.bl.kunderserver.de',
    'all.rbl.jp',
    'all.s5h.net',
    'all.spam-rbl.fr',
    'aspews.ext.sorbs.net',
    'auth.spamrats.com',
    'b.barracudacentral.org',
    'backscatter.spameatingmonkey.net',
    'bad.psky.me',
    'bl.blocklist.de',
    'bl.drmx.org',
    'bl.emailbasura.org',
    'bl.fmb.la',
    'bl.konstant.no',
    'bl.mailspike.net',
    'bl.mipspace.com',
    'bl.nszones.com',
    'bl.scientificspam.net',
    'bl.score.senderscore.com',
    'bl.spamcannibal.org',
    'bl.spamcop.net',
    'bl.spameatingmonkey.net',
    'bl.spamstinks.com',
    'bl.suomispam.net',
    'bl.tiopan.com',
    'hostkarma.junkemailfilter.com'
]
